version: '3.7'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: jwt_spring_application_docker
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"

    volumes:
      # Just specify a path and let the Engine create a volume
      # - /var/lib/mysql
      - ./mysqlPersistenceVolume:/var/lib/mysql

  minio:
    image: quay.io/minio/minio # #minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
      #volumes:
      #- ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set miniobucket http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb miniobucket/bucket;
      /usr/bin/mc policy set public miniobucket/bucket;
      exit 0;"

  app:
    image: app
    ports:
      - "8081:8081"

    environment:
      #SPRING_DATASOURCE_URL:jdbc: jdbc:mysql://localhost:3310/jwt_spring_application_docker?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_URL:jdbc: jdbc:mysql://database:3306/jwt_spring_application_docker?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_USERNAME: "root"
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - database
      - minio
      - createbuckets

    #command: sh -c './wait-for minio:9000 -- java -jar app.jar'
    entrypoint: [ "/wait-for-it.sh", "database:3306",  "-t", "120", "--", "java", "-jar", "app.jar" ]

